version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 425302025161.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=425302025161.dkr.ecr.ap-south-1.amazonaws.com/magixrepo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on date
      - echo Building the Docker image...
      - docker build -f dockerfile -t magixrepo:latest .
      - docker tag tep-v3-ecr:nextjs-latest 078010589169.dkr.ecr.ap-south-1.amazonaws.com/tep-v3-ecr:nextjs-latest
      
  post_build:
    commands:
      - echo Build completed on date
      - echo Pushing the Docker Image...
      - docker push 078010589169.dkr.ecr.ap-south-1.amazonaws.com/magixrepo:latest
      - echo Writing image definitions file...
      - printf '[{"dogsworld":"node-tep","imageUri":"078010589169.dkr.ecr.ap-south-1.amazonaws.com/tep-v3-ecr:nextjs-latest"}]' > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
    files: imagedefinitions.json
